apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    app: jenkins-agent
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  imagePullSecrets:
    - name: docker.io
  containers:
    - name: docker
      image: docker:24.0.5-dind
      command: ["/bin/sh", "-c"]
      args:
        - apk add --no-cache git && dockerd-entrypoint.sh
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: jnlp
      image: jenkins/inbound-agent:latest
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: workspace-volume
      emptyDir: {}
