name: Build, Scan & Secure Docker Image with Email Notification and Manual Approval

on:
  push:
    branches: [ main, develop ]  # Triggers on push to main or develop branches

env:
  IMAGE_NAME: mangale/smart-ai

jobs:
  secure-build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get short commit SHA
      id: vars
      run: |
        echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        echo "image_tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker Image (No Push Yet)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

    - name: Scan Docker image with Trivy
      run: |
        trivy image \
          --severity CRITICAL,HIGH,MEDIUM \
          --ignore-unfixed \
          --format markdown \
          --output trivy-report.md \
          ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

    - name: Send Trivy Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: 🔒 Security Scan Report for ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
        to: ${{ secrets.APPROVER_EMAIL }}
        from: ${{ secrets.GMAIL_USERNAME }}
        html_body: |
          <h2>Docker Image Security Scan Report</h2>
          <p><strong>Repository:</strong> ${{ github.repository }}</p>
          <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
          <p><strong>Commit:</strong> ${{ github.sha }}</p>
          <p><strong>Image:</strong> ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}</p>
          <p><strong>Pushed by:</strong> ${{ github.actor }}</p>
          
          <h3>Trivy Security Scan Results:</h3>
          <pre style="background-color: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto;">
          $(cat trivy-report.md)
          </pre>
          
          <p>Please review the scan results and approve the deployment in GitHub Actions if the image is safe to push to registry.</p>
          <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
        attachments: trivy-report.md
        
  manual-approval:
    name: Await Manual Approval
    needs: secure-build
    runs-on: ubuntu-latest
    environment:
      name: production-approval  # Setuped in repo settings
    steps:
      - run: echo "Awaiting manual approval before pushing image..."

  push-image:
    name: Push Docker Image to Registry
    needs: [manual-approval, secure-build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ needs.secure-build.outputs.image_tag }}
