name: Build, Scan & Secure Docker Image for Production

on:
  push:
    branches: [main]
env:
  IMAGE_NAME: mangale/smart-ai

jobs:
  secure-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get short commit SHA
      id: vars
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image with SBOM
      run: |
        docker buildx build --push --sbom=true --tag ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

    - name: Scan Docker image with Trivy
      run: |
        trivy image \
          --severity CRITICAL,HIGH,MEDIUM \
          --format table \
          --ignore-unfixed \
          --output trivy-report.txt \
          $IMAGE_NAME:${{ env.SHORT_SHA }}

    - name: Send Trivy Report via Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Trivy Vulnerability Report - ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}"
        to: lopchanmangal5@gmail.com
        from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
        body: |
          Hello,

          Attached is the Trivy vulnerability report for ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}.

          - GitHub Actions (Production Grade)
        attachments: trivy-report.txt
